# Generated by Django 4.2.5 on 2023-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
