# Generated by Django 4.2.5 on 2023-10-18 12:43

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        upload_to=product.models.combo_image_directory_path
                    ),
                ),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("products", models.ManyToManyField(to="product.products")),
            ],
        ),
    ]
