# Generated by Django 4.2.5 on 2023-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_productday"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayweek",
            name="number_day",
            field=models.IntegerField(default=0),
        ),
    ]
