# Generated by Django 4.2.5 on 2023-10-23 08:41

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_products_supplements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="None",
                upload_to=product.models.category_image_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=product.models.combo_image_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="supplements",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=product.models.supplements_image_directory_path
            ),
        ),
    ]
