# Generated by Django 4.2.5 on 2023-10-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_products_composition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="short_description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
