# Generated by Django 4.2.5 on 2023-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_products_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="base_supplements",
            field=models.ManyToManyField(
                blank=True, related_name="supplemented_by", to="product.products"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="is_supplement",
            field=models.BooleanField(default=False),
        ),
    ]
