# Generated by Django 4.2.5 on 2023-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_combo_drinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
