# Generated by Django 4.2.5 on 2023-11-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="dimensions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.dimensions",
            ),
        ),
    ]
