# Generated by Django 4.2.5 on 2023-11-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0058_alter_adress_work_with_alter_adress_works_until"),
        ("product", "0017_products_dimensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("number_week", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProductWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.dayweek",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.shop"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.products",
                    ),
                ),
            ],
        ),
    ]
