# Generated by Django 4.2.5 on 2023-11-18 14:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_alter_productweek_day_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                default="null.png",
                upload_to=product.models.products_image_directory_path,
            ),
        ),
    ]
