# Generated by Django 4.2.5 on 2023-11-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_alter_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_multiple_supplements",
            field=models.BooleanField(default=False),
        ),
    ]
