# Generated by Django 5.0 on 2023-12-13 17:46

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0067_alter_adress_friday_until_alter_adress_friday_with_and_more'),
        ('product', '0021_products_is_multiple_supplements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'verbose_name_plural': 'Комбо'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name_plural': 'Состав'},
        ),
        migrations.AlterModelOptions(
            name='dayweek',
            options={'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterModelOptions(
            name='dimensions',
            options={'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='numberweek',
            options={'verbose_name_plural': 'Недели'},
        ),
        migrations.AlterModelOptions(
            name='productday',
            options={'verbose_name_plural': 'Товар дня'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productweek',
            options={'verbose_name_plural': 'Товар недели'},
        ),
        migrations.AlterModelOptions(
            name='supplements',
            options={'verbose_name_plural': 'Добавки'},
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка в %'),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.FloatField(default=0.0, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='None', upload_to=product.models.category_image_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='drinks', to='product.products', verbose_name='Товар для выбора'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.combo_image_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='new_price',
            field=models.FloatField(verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='old_price',
            field=models.FloatField(verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(to='product.products', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='text',
            field=models.TextField(verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='dayweek',
            name='number_day',
            field=models.IntegerField(default=0, verbose_name='Номер дня'),
        ),
        migrations.AlterField(
            model_name='dayweek',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='numberweek',
            name='number_week',
            field=models.IntegerField(default=0, verbose_name='Номер недели'),
        ),
        migrations.AlterField(
            model_name='numberweek',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productday',
            name='day_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.dayweek', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='productday',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='productday',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='products',
            name='base_supplements',
            field=models.ManyToManyField(blank=True, related_name='supplemented_by', to='product.products', verbose_name='Продукты как добавки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.composition', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dimensions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.dimensions', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='null.png', upload_to=product.models.products_image_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_multiple_supplements',
            field=models.BooleanField(default=False, verbose_name='Доступна одна добавка?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_supplement',
            field=models.BooleanField(default=False, verbose_name='Является добавкой?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplements',
            field=models.ManyToManyField(blank=True, to='product.supplements', verbose_name='Добавки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='productweek',
            name='day_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.numberweek', verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='productweek',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='productweek',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.supplements_image_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
