# Generated by Django 4.2.5 on 2023-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_prise_auto", models.IntegerField()),
                ("min_prise_people", models.IntegerField()),
            ],
        ),
    ]
