# Generated by Django 4.2.5 on 2023-10-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_alter_ordersettings_min_prise_auto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersettings",
            name="auto_free_delivery",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="auto_price_delivery",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="people_free_delivery",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ordersettings",
            name="people_price_delivery",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
