# Generated by Django 4.2.5 on 2023-10-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_ordersettings_auto_free_delivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.CharField(max_length=500)),
                ("sent_data", models.JSONField()),
                ("received_response", models.TextField()),
                ("status", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=500)),
                ("url", models.CharField(max_length=500)),
            ],
        ),
    ]
