# Generated by Django 4.2.5 on 2023-10-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0027_alter_adress_work_with_alter_adress_works_until"),
        ("settings", "0004_errorclient"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegaramBotForAdressMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                ("chanel", models.CharField(max_length=100)),
                (
                    "adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.adress"
                    ),
                ),
            ],
        ),
    ]
