# Generated by Django 4.2.5 on 2023-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_telegarambotforadressmarket"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegarambotforadressmarket",
            name="main_bot",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="telegarambotforadressmarket",
            name="chanel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="telegarambotforadressmarket",
            name="token",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
