# Generated by Django 4.2.5 on 2023-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_telegarambotforadressmarket_main_bot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegarambotforadressmarket",
            name="chanel",
            field=models.CharField(max_length=100),
        ),
    ]
