# Generated by Django 5.0 on 2023-12-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0065_alter_adress_options_alter_imageshop_options_and_more'),
        ('settings', '0008_ordersettings_people_long_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorclient',
            options={'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AlterModelOptions(
            name='ordersettings',
            options={'verbose_name_plural': 'Настройки заказов'},
        ),
        migrations.AlterModelOptions(
            name='telegarambotforadressmarket',
            options={'verbose_name_plural': 'Телеграмм чаты адресов'},
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='auto_free_delivery',
            field=models.BooleanField(default=True, verbose_name='Бесплатная доставка?'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='auto_price_delivery',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Цена атодоставки'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='min_prise_auto',
            field=models.FloatField(verbose_name='Минимальная сумма заказа для автодоставки'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='min_prise_people',
            field=models.FloatField(verbose_name='Минимальная сумма заказа для пешей доставки'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='people_free_delivery',
            field=models.BooleanField(default=True, verbose_name='Бесплатная доставка'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='people_long_delivery',
            field=models.IntegerField(default=1500, verbose_name='Дальность пешей доставки'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='people_price_delivery',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Цена пешей доставки'),
        ),
        migrations.AlterField(
            model_name='telegarambotforadressmarket',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.adress', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='telegarambotforadressmarket',
            name='chanel',
            field=models.CharField(max_length=100, verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='telegarambotforadressmarket',
            name='main_bot',
            field=models.BooleanField(default=True, verbose_name='Основной бот?'),
        ),
        migrations.AlterField(
            model_name='telegarambotforadressmarket',
            name='token',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключ от бота'),
        ),
    ]
