# Generated by Django 5.0 on 2023-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_errorclient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.IntegerField(default=0, verbose_name='Общая скидка в %')),
            ],
            options={
                'verbose_name_plural': 'Настройки товаров',
            },
        ),
    ]
