# Generated by Django 5.0 on 2023-12-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_allproductssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField(default=False, verbose_name='Режим разработки')),
                ('is_disabled_cart', models.BooleanField(default=False, verbose_name='Отключить корзину')),
                ('is_disabled_online_pyment', models.BooleanField(default=False, verbose_name='Отключить онлайн оплату')),
                ('is_disabled_cash_pyment', models.BooleanField(default=False, verbose_name='Отключить отплату наличными')),
                ('is_disabled_auto_delivery', models.BooleanField(default=False, verbose_name='Отключить автодоставку')),
                ('is_disabled_people_delivery', models.BooleanField(default=False, verbose_name='Отклюить пешую доставку')),
                ('is_disabled_pickup_delivery', models.BooleanField(default=False, verbose_name='Отключить самовывоз')),
                ('is_disabled_reservation', models.BooleanField(default=False, verbose_name='Отключить бронирование столиков')),
                ('is_disabled_order', models.BooleanField(default=False, verbose_name='Отключить бронирование столиков')),
            ],
            options={
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
    ]
