# Generated by Django 4.2.5 on 2023-11-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market", "0046_alter_adress_work_with_alter_adress_works_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=10)),
                ("count_guest", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.shop"
                    ),
                ),
            ],
        ),
    ]
