# Generated by Django 4.2.5 on 2023-11-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0047_alter_adress_work_with_alter_adress_works_until"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingmodel",
            name="shop",
        ),
        migrations.AddField(
            model_name="bookingmodel",
            name="adress",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.adress",
            ),
        ),
    ]
