# Generated by Django 4.2.5 on 2023-11-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0048_alter_adress_work_with_alter_adress_works_until"),
        ("booking", "0002_remove_bookingmodel_shop_bookingmodel_adress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListBooing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.adress"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bookingmodel",
            name="adress",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.listbooing",
            ),
        ),
    ]
