# Generated by Django 4.2.5 on 2023-11-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0051_alter_adress_work_with_alter_adress_works_until"),
        ("booking", "0003_listbooing_alter_bookingmodel_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="listbooing",
            name="siti",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="market.siti"
            ),
        ),
    ]
