# Generated by Django 4.2.5 on 2023-11-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_listbooing_siti"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmodel",
            name="date",
            field=models.CharField(default=1, max_length=20),
        ),
    ]
