# Generated by Django 5.0 on 2023-12-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingmodel_date'),
        ('market', '0064_alter_adress_friday_until_alter_adress_friday_with_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'verbose_name_plural': 'Заявки на бронирование'},
        ),
        migrations.AlterModelOptions(
            name='listbooing',
            options={'verbose_name_plural': 'Адреса для бронирования'},
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.listbooing', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='count_guest',
            field=models.IntegerField(verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.CharField(default=1, max_length=20, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='listbooing',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.adress', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='listbooing',
            name='siti',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='market.siti', verbose_name='Город'),
        ),
    ]
