# Generated by Django 4.2.5 on 2023-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lk", "0002_adress_lat_adress_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="is_activ",
            field=models.BooleanField(default=True),
        ),
    ]
