# Generated by Django 4.2.5 on 2023-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lk", "0004_alter_profile_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="adress",
            field=models.ManyToManyField(blank=True, to="lk.adress"),
        ),
    ]
