# Generated by Django 4.2.5 on 2023-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lk", "0005_alter_profile_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="apartment",
            field=models.IntegerField(blank=True, default="1"),
        ),
        migrations.AddField(
            model_name="adress",
            name="door_code",
            field=models.IntegerField(blank=True, default="1"),
        ),
        migrations.AddField(
            model_name="adress",
            name="entrance",
            field=models.IntegerField(blank=True, default="1"),
        ),
        migrations.AddField(
            model_name="adress",
            name="floor",
            field=models.IntegerField(blank=True, default="1"),
        ),
    ]
