# Generated by Django 5.0 on 2023-12-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_alter_adress_apartment_alter_adress_door_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress',
            field=models.CharField(max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='apartment',
            field=models.IntegerField(blank=True, default='0', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='door_code',
            field=models.IntegerField(blank=True, default='0', verbose_name='Код двери'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='entrance',
            field=models.IntegerField(blank=True, default='0', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='floor',
            field=models.IntegerField(blank=True, default='0', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='long',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.ManyToManyField(blank=True, to='lk.adress', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
