# Generated by Django 4.2.5 on 2023-10-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lk", "0003_adress_is_activ"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrderHystory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField()),
                ("is_pyment", models.BooleanField(default=False)),
                ("is_activ", models.BooleanField(default=True)),
                (
                    "adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lk.adress"
                    ),
                ),
                ("products", models.ManyToManyField(to="cart.productsincart")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
