# Generated by Django 4.2.5 on 2023-10-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_deliverytype_pymenttype_userorderhystory_is_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorderhystory",
            name="delivery_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.deliverytype",
            ),
        ),
        migrations.AddField(
            model_name="userorderhystory",
            name="pyment_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.pymenttype",
            ),
        ),
    ]
