# Generated by Django 4.2.5 on 2023-10-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_userorderhystory_delivery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorderhystory",
            name="pyment_id",
            field=models.CharField(blank=True, default="None", max_length=700),
        ),
    ]
