# Generated by Django 4.2.5 on 2023-10-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0017_alter_adress_work_with_alter_adress_works_until"),
        ("lk", "0003_adress_is_activ"),
        ("order", "0007_userorderhystory_time_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorderhystory",
            name="market_adress_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.adress",
            ),
        ),
        migrations.AlterField(
            model_name="userorderhystory",
            name="adress",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="lk.adress"
            ),
        ),
    ]
