# Generated by Django 4.2.5 on 2023-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_alter_productsincart_combo"),
        ("order", "0009_alter_userorderhystory_market_adress_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorderhystory",
            name="combos",
            field=models.ManyToManyField(to="cart.comboincart"),
        ),
    ]
