# Generated by Django 4.2.5 on 2023-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_alter_productsincart_combo"),
        ("order", "0010_userorderhystory_combos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorderhystory",
            name="products",
            field=models.ManyToManyField(blank=True, to="cart.productsincart"),
        ),
    ]
