# Generated by Django 4.2.5 on 2023-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_userorderhystory_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorderhystory",
            name="change_with",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
