# Generated by Django 5.0 on 2023-12-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartuser_options_alter_comboincart_options_and_more'),
        ('lk', '0008_alter_adress_options_alter_profile_options_and_more'),
        ('market', '0065_alter_adress_options_alter_imageshop_options_and_more'),
        ('order', '0012_userorderhystory_change_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name_plural': 'Типы доставки'},
        ),
        migrations.AlterModelOptions(
            name='pymenttype',
            options={'verbose_name_plural': 'Типы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='userorderhystory',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pymenttype',
            name='is_payment',
            field=models.BooleanField(default=True, verbose_name='Требует оплаты?'),
        ),
        migrations.AlterField(
            model_name='pymenttype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='adress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lk.adress', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='change_with',
            field=models.FloatField(blank=True, default=0, verbose_name='Сдача с'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='combos',
            field=models.ManyToManyField(to='cart.comboincart', verbose_name='Комбо'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.deliverytype', verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='is_call',
            field=models.BooleanField(default=True, verbose_name='Требуется звонок?'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='is_pyment',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='market_adress_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.adress', verbose_name='Адрес приготовления'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='products',
            field=models.ManyToManyField(blank=True, to='cart.productsincart', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='pyment_id',
            field=models.CharField(blank=True, default='None', max_length=700, verbose_name='Номер оплаты'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='pyment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.pymenttype', verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='time_delivery',
            field=models.CharField(blank=True, default='None', max_length=50, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='userorderhystory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
