# Generated by Django 4.2.5 on 2023-10-18 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_timezone_alter_adress_work_with_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="timezone",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.timezone",
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 12, 13, 11, 817078)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 12, 13, 11, 817078)
            ),
        ),
    ]
