# Generated by Django 4.2.5 on 2023-10-18 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_adress_timezone_alter_adress_work_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 12, 27, 35, 391427)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 12, 27, 35, 391427)
            ),
        ),
    ]
