# Generated by Django 4.2.5 on 2023-10-18 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_combo"),
        ("market", "0010_alter_adress_work_with_alter_adress_works_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="combo",
            field=models.ManyToManyField(to="product.combo"),
        ),
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 15, 43, 6, 571887)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 18, 15, 43, 6, 571887)
            ),
        ),
    ]
