# Generated by Django 4.2.5 on 2023-10-23 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_products_composition"),
        ("market", "0023_alter_adress_work_with_alter_adress_works_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 23, 12, 18, 23, 587809)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 10, 23, 12, 18, 23, 587809)
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="combo",
            field=models.ManyToManyField(blank=True, to="product.combo"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="link",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="shop",
            name="short_description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
