# Generated by Django 4.2.5 on 2023-11-15 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0054_alter_adress_work_with_alter_adress_works_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_front_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 50, 59, 564707)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 50, 59, 564707)
            ),
        ),
    ]
