# Generated by Django 4.2.5 on 2023-11-15 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0055_shop_shop_front_id_alter_adress_work_with_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="shop_front_id",
        ),
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 53, 53, 521951)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 53, 53, 521951)
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="link",
            field=models.IntegerField(default=1),
        ),
    ]
