# Generated by Django 4.2.5 on 2023-11-15 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_products_dimensions"),
        ("market", "0056_remove_shop_shop_front_id_alter_adress_work_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 55, 54, 546454)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 15, 11, 55, 54, 546454)
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="products",
            field=models.ManyToManyField(blank=True, to="product.products"),
        ),
    ]
