# Generated by Django 4.2.5 on 2023-11-16 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0060_alter_adress_work_with_alter_adress_works_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="phone",
            field=models.CharField(default=79991112233, max_length=15),
        ),
        migrations.AlterField(
            model_name="adress",
            name="work_with",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 16, 3, 51, 28, 814897)
            ),
        ),
        migrations.AlterField(
            model_name="adress",
            name="works_until",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 16, 3, 51, 28, 814897)
            ),
        ),
    ]
