# Generated by Django 4.2.5 on 2023-11-18 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0061_adress_phone_alter_adress_work_with_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adress",
            name="work_with",
        ),
        migrations.RemoveField(
            model_name="adress",
            name="works_until",
        ),
        migrations.AddField(
            model_name="adress",
            name="friday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="is_around_clock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adress",
            name="monday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="saturday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="sunday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="thursday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="tuesday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="wednesday",
            field=models.TimeField(
                default=datetime.datetime(2023, 11, 18, 17, 56, 37, 95228)
            ),
        ),
    ]
