# Generated by Django 5.0 on 2023-12-13 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0065_alter_adress_options_alter_imageshop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='friday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Пятница до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='friday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Пятница с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='monday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Понедельник до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='monday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Понедельник с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='saturday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Суббота до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='saturday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Суббота с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='sunday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Воскресенье до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='sunday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Воскресенье с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='thursday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Четверг до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='thursday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Четвер с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='tuesday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Вторник до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='tuesday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Вторник с'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='wednesday_until',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Среда до'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='wednesday_with',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 20, 46, 17, 744860), verbose_name='Среда с'),
        ),
    ]
