# Generated by Django 4.2.5 on 2023-10-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_products_composition"),
        ("cart", "0002_supplementsincart_alter_productsincart_supplements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsincart",
            name="supplements",
            field=models.ManyToManyField(blank=True, to="cart.supplementsincart"),
        ),
        migrations.AlterField(
            model_name="supplementsincart",
            name="supplements",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.supplements",
            ),
        ),
    ]
