# Generated by Django 4.2.5 on 2023-10-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_combo_drinks"),
        ("cart", "0003_alter_productsincart_supplements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsincart",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.combo",
            ),
        ),
        migrations.CreateModel(
            name="ComboInCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(blank=True)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.combo"
                    ),
                ),
                (
                    "selected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.products",
                    ),
                ),
            ],
        ),
    ]
