# Generated by Django 4.2.5 on 2023-10-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_combo_drinks"),
        ("cart", "0004_productsincart_combo_comboincart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsincart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.products",
            ),
        ),
    ]
