# Generated by Django 4.2.5 on 2023-10-30 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_productsincart_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comboincart",
            name="count",
        ),
    ]
