# Generated by Django 4.2.5 on 2023-10-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_productsincart_is_combo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsincart",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.comboincart",
            ),
        ),
    ]
