# Generated by Django 5.0 on 2023-12-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_productsincart_combo'),
        ('product', '0021_products_is_multiple_supplements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartuser',
            options={'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='comboincart',
            options={'verbose_name_plural': 'Комбо в корзине'},
        ),
        migrations.AlterModelOptions(
            name='productsincart',
            options={'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='supplementsincart',
            options={'verbose_name_plural': 'Добавки в корзине'},
        ),
        migrations.AlterField(
            model_name='cartuser',
            name='products',
            field=models.ManyToManyField(to='cart.productsincart', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='cartuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comboincart',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.combo', verbose_name='Комбо'),
        ),
        migrations.AlterField(
            model_name='comboincart',
            name='selected_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Выбранный продукт'),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.comboincart', verbose_name='Комбо в корзине'),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='is_combo',
            field=models.BooleanField(default=False, verbose_name="Является 'комбо'?"),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='supplements',
            field=models.ManyToManyField(blank=True, to='cart.supplementsincart', verbose_name='Добавки'),
        ),
        migrations.AlterField(
            model_name='supplementsincart',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='supplementsincart',
            name='supplements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supplements', verbose_name='Добавки'),
        ),
    ]
